bookie-ui/config/routes.rb
BookieUi::Application.routes.draw do

  root to: 'jobs#index'

  resources :jobs
  resources :systems
  resources :users

  resource :graph, only: [:show]

  resources :web_users
  resources :password_resets

  resource :session
end

bookie-ui/app/models/web_user.rb
class WebUser < ActiveRecord::Base
  attr_reader :password

  #TODO: better email validation?
  validates :email, format: { :with => /@/ }
  validates :email, uniqueness: { message: 'is already in use.' }
  validates :password, confirmation: true

  def password=(password)
    @password ||= password
    if password.blank?
      self.password_salt = nil
      self.password_hash = nil
    else
      self.password_salt = SecureRandom.urlsafe_base64
      self.password_hash = self.hash_password(self.password)
    end
  end

  ##
  #Hashes the given password using this user's password salt
  def hash_password(password)
    Digest::SHA512.hexdigest(password + self.password_salt)
  end

  def confirmed?
    self.password_hash != nil
  end

  def generate_reset_key
    reset_key = SecureRandom.urlsafe_base64
    #To consider: include salt?
    self.reset_key_hash = Digest::SHA512.hexdigest(reset_key)
    self.reset_sent_at = Time.zone.now
    reset_key
  end

  ##
  #Resets the reset_key_hash and reset_sent_at fields to nil
  #
  #Does not save the record
  def clear_reset_key
    self.reset_key_hash = nil
    self.reset_sent_at = nil
  end

  def correct_reset_key?(reset_key)
    key_hash = Digest::SHA512.hexdigest(reset_key)
    self.reset_key_hash == key_hash
  end

  def reset_key_expired?
    !reset_sent_at || (Time.zone.now - reset_sent_at) > 1.days
  end

  def self.authenticate(email, password)
    web_user = where(email: email).first
    if web_user && web_user.password_hash == web_user.hash_password(password)
      web_user
    else
      nil
    end
  end
end

bookie-ui/app/controllers/web_users_controller.rb
class WebUsersController < ApplicationController
  before_filter :require_login

  def new
    @web_user = WebUser.new
  end

  def create
    user_params = params[:web_user].permit(:email)
    @web_user = WebUser.new(user_params)
    if @web_user.valid?
      key = @web_user.generate_reset_key
      @web_user.save!
      WebUserMailer.confirmation(@web_user, key).deliver
      flash_msg :notice, 'User created.'
      redirect_to web_users_path
    else
      render action: 'new'
    end
  end

  def index
    @web_users = WebUser.where(nil)
  end

  def destroy
    redirect_to web_users_path
    web_user = WebUser.where(id: params[:id]).first
    unless web_user
      flash_msg :error, 'Unable to find user.'
      return
    end

    confirmed_web_users = WebUser.where.not(password_hash: nil)
    if confirmed_web_users.count == 1 && web_user.confirmed?
      #Don't delete the last confirmed user.
      flash_msg :error, 'Unable to delete user: there must always be at least one confirmed user.'
    else
      #TODO: handle self-deletions more gracefully.
      flash_msg :notice, 'User deleted.'
      web_user.destroy
    end
  end
end

bookie-ui/app/views/web_users/index.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "list", :media => "all" %>
  <style type="text/css">
    table {
      width: auto;
    }
  </style>
<% end %>

<% content_for :heading do %>Web Users<% end %>

<div id="main">
  <div id="content">
    <table id="web_users" class = "list">
      <tr>
        <th>E-mail address</th>
        <th>Confirmed?</th>
        <th>Actions</th>
      </tr>
      <% @web_users.each do |web_user| %>
        <tr>
          <td><%= web_user.email %></td>
          <td><%= if web_user.confirmed? then 'Yes' else 'No' end %></td>
          <td><%= link_to 'Delete', web_user_path(web_user.id), method: :delete %></td>
        </tr>
      <% end %>
    </table>
    <%= link_to 'New user', new_web_user_path %>
  </div>
</div>

bookie-ui/app/views/web_users/new.html.erb
<% content_for :heading, 'New user' %>

<%= form_for @web_user do |f| %>
  <%= form_errors(@web_user.errors) %>
  <%= f.label :email %></br>
  <%= f.email_field :email %><br/>
  <%= f.submit %>
<% end %>