bookie-ui/config/routes.rb
BookieUi::Application.routes.draw do

  root to: 'jobs#index'

  resources :jobs
  resources :systems
  resources :users

  resource :graph, only: [:show]

  resources :web_users
  resources :password_resets

  resource :session
end

bookie-ui/app/controllers/systems_controller.rb
require 'bookie_database_all'

class SystemsController < ApplicationController
  before_filter :require_login

  def index
    @systems = Bookie::Database::System.order(:name)
  end

  #TODO: implement.
  def show
    #@system = Bookie::Database::System.find
  end

  def new
    @system = Bookie::Database::System.new
  end

  def create
    sys_params = params[:system].permit(:hostname, :system_type)
    @system = Bookie::Database::System.new(sys_params)
    if @system.valid?
      @system.save!
      flash_msg :notice, 'System created.'
      redirect_to systems_path
    else
      render action: 'new'
    end
  end
end

bookie-ui/app/views/systems/index.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'list', media: 'all' %>
<% end %>

<% content_for :heading do %>Systems<% end %>

<div id="main">
  <table id="systems" class="list">
    <tr>
      <th>Hostname</th>
      <th>Type</th>
      <th>Active</th>
    </tr>
    <% @systems.each do |system| %>
      <tr>
        <td><%= link_to system.name, @system %></td>
        <td><%= system.system_type.name %></td>
        <td><%= if system.active? then 'yes' else 'no' end %></td>
      </tr>
    <% end %>
  </table>
  <%= link_to 'New system', new_system_path %>
</div>