bookie-ui/config/routes.rb
BookieUi::Application.routes.draw do

  root to: 'jobs#index'

  resources :jobs
  resources :systems
  resources :users

  resource :graph, only: [:show]

  resources :web_users
  resources :password_resets

  resource :session
end

bookie-ui/app/views/shared/_filter.html.erb
<div class="filter">
  <span class="filter_type"><%= name.to_s.humanize %></span>
  <div class="filter_remover"></div>
  <%= render partial: "shared/filter_inputs/#{filter_type}", locals: {
    name: name,
    values: values
  } %>
</div>

bookie-ui/app/views/shared/_filter_errors.html.erb
<% if errors.length > 0 %>
  <div id="filter_errors">
  <h2>Filter errors</h2>
  <ul>
    <% errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
</div>
<% end %>

bookie-ui/app/views/shared/_filter_errors.json.erb
"filter_errors": [
  <%= raw(errors.map{ |e| ActiveSupport::JSON::Encoding.escape(e) }.join(",\n")) %>
]

bookie-ui/app/views/shared/_filter_prototype.html.erb
<div id="filter_prototype_<%= name %>">
  <%= render partial: "shared/filter_inputs/#{filter_type}", locals: {
    name: name,
    values: []
  } %>
</div>

bookie-ui/app/views/shared/_filters.html.erb
<div id="controls">
  <h2>Filters</h2>
  <% displayed_filters = Set.new %>
  <%= form_tag("", method: 'get', id: 'filter_form') do %>
    <span id="filters">
      <% if @prev_filters %>
        <% @prev_filters.each do |name, values| %>
          <% value_type = filter_types[name] %>
          <%= filter_for(name, value_type, values) %>
          <% displayed_filters.add(name) %>
        <% end %>
      <% end %>
    </span>
    <select id="add_filter">
      <option value="">Add filter</option>
      <% filter_types.each do |name, value_type| %>
        <% #The value attribute is hijacked to hold the internal name of the filter. %>
        <option value="<%= name %>" <% if displayed_filters.include?(name) %>disabled="disabled"<% end %>>
          <%= name.to_s.humanize %>
        </option>
      <% end %>
    </select>
    <% if defined? show_details %>
      <label><%= check_box_tag("show_details", "true", show_details) %>Show details</label>
    <% end %>
    <%= submit_tag("Filter") %>
  <% end %>
  <% #For each type of filter, a prototype is added to the page in a hidden div. %>
  <div id="filter_prototypes">
    <% filter_types.each do |name, value_type| %>
      <%= filter_prototype_for(name, value_type) %>
    <% end %>
  </div>
</div>

bookie-ui/app/views/shared/_form_errors.html.erb
<% if errors.any? %>
  <div class="form_errors">
    <ul>
      <% errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

bookie-ui/app/views/shared/_navbar.html.erb
<div id="navigation">
  <ul>
    <li><%= link_to 'Jobs', jobs_path %>
      <ul>
        <li><%= link_to 'Summary', jobs_path %></li>
        <li><%= link_to 'Graphs', graph_path %></li>
      </ul>
    </li>
    <li><%= link_to 'Systems', systems_path %></li>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'Web users', web_users_path %></li>
  </ul>
  <ul id="account_tools">
    <li>
      <% if current_web_user %>
        <%= current_web_user.email %>
        <ul>
          <li><%= link_to 'Log out', session_path, method: :delete %></li>
          <li><%= link_to 'Change password', edit_web_user_path(current_web_user) %></li>
        </ul>
      <% else %>
        <%= link_to 'Log in', new_session_path %>
      <% end%>
    </li>
  </ul>
</div>

bookie-ui/app/views/shared/_pages.html.erb
<% if @page_num && @num_pages %>
  <label for="select_page">Page:</label>
  <select id="select_page">
    <% (1 .. @num_pages).each do |i| %>
      <option value="<%= i %>" <%= 'selected=selected' if i == @page_num %>><%= i %></option>
    <% end %>
  </select>
<% end %>